import mongoose, { Document, Schema } from "mongoose"

type Message = {
    message: string
    senderId: string
    timestamp: Date
}

interface IChatSession extends Document {
    user1: string
    user2: string
    messages: Message[]
}

// use mongodb autogenerated id as chatId
let ChatSessionSchema: Schema = new Schema({
    user1: { type: String, required: true },
    user2: { type: String, required: true },
    messages: { type: [Object], required: true }
})

const ChatSession: mongoose.Model<IChatSession> = mongoose.model<IChatSession>('ChatSession', ChatSessionSchema)

export { ChatSession, IChatSession }